spring:
  mvc:
    locale: en_US
  jpa:
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/bills_to_pay
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://postgres:5432/bills_to_pay
    user: postgres
    password: postgres
    schemas: public
    out-of-order: true
    locations: classpath:database